"""Pydantic data models for Amazon Bedrock Root Cause Analysis (RCA).

Phase 7: Diagnostic Evidence, AI Output Schema, and Deterministic Safety Contracts.
"""

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class EvidenceSource(str, Enum):
    """Categorized sources of diagnostic telemetry evidence."""
    NEW_RELIC_INCIDENT = "NEW_RELIC_INCIDENT"
    APPLICATION_LOGS = "APPLICATION_LOGS"
    DISTRIBUTED_TRACES = "DISTRIBUTED_TRACES"
    INFRASTRUCTURE_METRICS = "INFRASTRUCTURE_METRICS"
    HEALTH_CHECK = "HEALTH_CHECK"
    AUDIT_HISTORY = "AUDIT_HISTORY"


class RecommendationDecision(str, Enum):
    """Deterministic validation decisions for AI recommendations."""
    ALLOWLISTED_RECOMMENDATION = "ALLOWLISTED_RECOMMENDATION"
    REJECTED_RECOMMENDATION = "REJECTED_RECOMMENDATION"
    NO_ACTION_REQUIRED = "NO_ACTION_REQUIRED"


class TelemetryEvidence(BaseModel):
    """Diagnostic evidence gathered for root cause analysis."""

    incident_id: Optional[str] = Field(default=None, description="New Relic or system incident identifier")
    condition_name: Optional[str] = Field(default=None, description="Triggering alert condition name")
    incident_state: Optional[str] = Field(default=None, description="Current incident lifecycle state (e.g. ACTIVATED, CLOSED)")
    health_status: Optional[str] = Field(default=None, description="Recent /health endpoint response or status")
    application_logs: List[str] = Field(default_factory=list, description="Recent application log lines")
    error_logs: List[str] = Field(default_factory=list, description="Recent error logs or traceback extracts")
    trace_spans: List[Dict[str, Any]] = Field(default_factory=list, description="OpenTelemetry / New Relic trace span details")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Infrastructure metrics (CPU, memory, latency, error rate)")
    version_info: Optional[str] = Field(default=None, description="Application and deployment version identifier")
    remediation_history: List[Dict[str, Any]] = Field(default_factory=list, description="Recent remediation/audit actions recorded")
    raw_metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional unstructured contextual metadata")


class RCARequest(BaseModel):
    """Request payload submitted for Bedrock AI root cause analysis."""

    incident_id: str = Field(..., description="Unique incident identifier to analyze", min_length=1)
    evidence: TelemetryEvidence = Field(default_factory=TelemetryEvidence, description="Structured diagnostic evidence")
    context: Optional[Dict[str, Any]] = Field(default=None, description="Optional extra execution context")


class BedrockRawRCAOutput(BaseModel):
    """Strict schema for validating raw JSON responses generated by Amazon Bedrock."""

    incident_id: str = Field(..., description="Correlated incident ID")
    service: str = Field(..., description="Target service name under investigation")
    severity: str = Field(default="MEDIUM", description="Assessed incident severity level")
    root_cause: str = Field(..., description="Specific, concise identification of root cause")
    evidence: List[str] = Field(default_factory=list, description="List of factual evidence points supporting root cause")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score from 0.0 to 1.0")
    recommended_action: str = Field(..., description="Remediation action proposed by AI")
    recommended_target: str = Field(..., description="Proposed target infrastructure identifier")
    recommended_service: str = Field(..., description="Proposed target service identifier")
    reasoning_summary: str = Field(..., description="Clear explanation of the analytical chain of thought")

    @field_validator("confidence")
    @classmethod
    def validate_confidence_range(cls, v: float) -> float:
        if not (0.0 <= v <= 1.0):
            raise ValueError("Confidence score must be between 0.0 and 1.0")
        return round(v, 4)


class RCAResponse(BaseModel):
    """Final auditable Root Cause Analysis response with deterministic safety boundary validation."""

    incident_id: str = Field(..., description="Incident ID analyzed")
    service: str = Field(default="Ops23-NR", description="Target service name")
    severity: str = Field(default="MEDIUM", description="Assessed severity (CRITICAL, HIGH, MEDIUM, LOW, INFO)")
    root_cause: str = Field(..., description="Identified root cause or INSUFFICIENT_EVIDENCE")
    evidence: List[str] = Field(default_factory=list, description="Factual evidence items supporting conclusion")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Confidence score")
    recommended_action: str = Field(default="NONE", description="Recommended action")
    recommended_target: str = Field(default="NONE", description="Recommended target")
    recommended_service: str = Field(default="NONE", description="Recommended service")
    reasoning_summary: str = Field(..., description="Analytical reasoning summary")
    decision: RecommendationDecision = Field(
        default=RecommendationDecision.REJECTED_RECOMMENDATION,
        description="Deterministic validation outcome of AI recommendation",
    )
    execution_allowed: bool = Field(
        default=False,
        description="Strict safety flag: Phase 7 is analysis only; execution is always False",
    )
    model_id: Optional[str] = Field(default=None, description="Bedrock model identifier used for inference")
    analyzed_at: str = Field(..., description="ISO 8601 UTC timestamp of analysis completion")
    safety_validation_message: str = Field(
        default="Analysis complete. Execution not permitted from AI analysis layer.",
        description="Detailed explanation of the safety boundary assessment",
    )
